ALTER TYPE "BoostPlacement" ADD VALUE IF NOT EXISTS 'TOP_LISTING';
ALTER TYPE "BoostPlacement" ADD VALUE IF NOT EXISTS 'HIGHLIGHTED_LISTING';
ALTER TYPE "BoostPlacement" ADD VALUE IF NOT EXISTS 'CATEGORY_PRIORITY';
ALTER TYPE "BoostPlacement" ADD VALUE IF NOT EXISTS 'HOMEPAGE_PROMOTION';
ALTER TYPE "BoostPlacement" ADD VALUE IF NOT EXISTS 'TIME_BASED_BOOST';
